[workspace]
resolver = "2"
members = ["noir-r1cs", "merkle-hash-bench"]

[workspace.package]
edition = "2021"
rust-version = "1.85"
authors = [
    "Remco Bloemen <remco@world.org>",
    "Philipp Sippl <philipp@world.org>",
]
license = "MIT"
homepage = "https://github.com/worldfnd/ProveKit"
repository = "https://github.com/worldfnd/ProveKit"

[workspace.lints.rust]
unsafe_code = "warn"
missing_docs = "warn"

[workspace.lints.clippy]
all = "warn"
pendatic = "warn"
nursery = "warn"
cargo = "warn"
perf = "warn"
complexity = "warn"
style = "warn"
correctness = "warn"
suspicous = "warn"
missing_docs_in_private_items = { level = "allow", priority = 1 }

[profile.release]
debug = true # Generate symbol info for profiling

# Doing light optimizations helps test performance more than it hurts build time.
[profile.test]
opt-level = 2

# Compilation profile for any non-workspace member. We want to optimize these even in debug mode.
[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies]
anyhow = "1.0.93"
argh = "0.1.12"
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "ansi"] }
base64 = "0.22.1"
ruint = { version = "1.12.3", features = ["num-traits", "rand"] }
rand = "0.8.5"
subtle = "2.6.1"
bytemuck = "1.19.0"
hex-literal = "0.4.1"
itertools = "0.13.0"
flate2 = "1.0"
bincode = "1.3"


# Noir lang: make sure it matches installed version `noirup -C 03b58fa2`
acir = { git = "https://github.com/noir-lang/noir", rev = "03b58fa2" }
acvm = { git = "https://github.com/noir-lang/noir", rev = "03b58fa2" }
acir_field = { git = "https://github.com/noir-lang/noir", rev = "03b58fa2" }
noirc_abi = { git = "https://github.com/noir-lang/noir", rev = "03b58fa2" }
noirc_artifacts = { git = "https://github.com/noir-lang/noir", rev = "03b58fa2" }
noirc_printable_type = { git = "https://github.com/noir-lang/noir", rev = "03b58fa2" }

# WHIR
whir = { git = "https://github.com/WizardOfMenlo/whir" }
spongefish = { git = "https://github.com/arkworks-rs/spongefish", features = [
    "arkworks-algebra",
] }
ark-ff = { version = "0.5", features = ["asm", "std"] }
zeroize = "1.8.1"
ark-crypto-primitives = { version = "0.5", features = ["merkle_tree"] }
spongefish-pow = { git = "https://github.com/arkworks-rs/spongefish" }
ark-poly = "0.5"
ark-std = { version = "0.5", features = ["std"] }
ark-serialize = "0.5"

[patch.crates-io]
ruint = { git = "https://github.com/recmo/uint", branch = "main" }
