[package]
name = "poseidon2"
type = "bin"
compiler_version = ">=1.0.0"

[dependencies]
poseidon2 = { tag = "main", git = "https://github.com/TaceoLabs/noir-poseidon", directory = "poseidon2"}
ec = { tag = "v0.1.2", git = "https://github.com/noir-lang/ec" }
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }