name: Benchmark on Raspberry Pi 5

on:
  schedule: # Runs at midnight (0:00 UTC) every day
    - cron: "0 0 * * *"
  push:
    branches: [main]
  pull_request:

env:
  DIVAN_MAX_TIME: 30
  CODSPEED_RUNNER_MODE: walltime

jobs:
  build:
    name: Build benchmark binaries and poseidon_1000 artifacts
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v1
        with:
          channel: nightly-2025-04-05
          cache-base: main
          cache-target: release
          bins: cargo-codspeed

      - name: Setup Noir toolchain
        uses: noir-lang/noirup@v0.1.2
        with:
          toolchain: v1.0.0-beta.11

      - name: Build the benchmark target(s)
        timeout-minutes: 30
        run: cargo codspeed build

      - name: Upload benchmark binaries
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-binaries
          path: target/codspeed

      - name: Compile and execute Nargo circuit
        working-directory: noir-examples/poseidon-rounds
        run: |
          nargo compile --skip-brillig-constraints-check --force
          nargo execute

      - name: Create posiedon rounds 1000 files
        run: |
          cargo run --release --bin provekit-cli prepare ./noir-examples/poseidon-rounds/target/basic.json -p ./noir-examples/poseidon-rounds/noir-provekit-prover.pkp -v ./noir-examples/poseidon-rounds/noir-provekit-verifier.pkv
          cargo run --release --bin provekit-cli prove ./noir-examples/poseidon-rounds/noir-provekit-prover.pkp ./noir-examples/poseidon-rounds/Prover.toml -o ./noir-examples/poseidon-rounds/noir-proof.np
          cargo run --release --bin provekit-cli generate-gnark-inputs ./noir-examples/poseidon-rounds/noir-provekit-prover.pkp ./noir-examples/poseidon-rounds/noir-proof.np --params ./noir-examples/poseidon-rounds/params_for_recursive_verifier --r1cs ./noir-examples/poseidon-rounds/r1cs.json

      - name: Prepare poseidon artifacts directory
        run: |
          mkdir -p ./poseidon-artifacts
          cp ./noir-examples/poseidon-rounds/noir-provekit-prover.pkp ./poseidon-artifacts/
          cp ./noir-examples/poseidon-rounds/noir-provekit-verifier.pkv ./poseidon-artifacts/
          cp ./noir-examples/poseidon-rounds/noir-proof.np ./poseidon-artifacts/
          cp ./noir-examples/poseidon-rounds/r1cs.json ./poseidon-artifacts/

      - name: Upload poseidon-1000 files
        uses: actions/upload-artifact@v4
        with:
          name: poseidon-1000-files
          path: ./poseidon-artifacts/

  benchmark:
    name: Run benchmarks on Raspberry Pi 5
    runs-on: [self-hosted, rpi5]
    needs: build
    steps:
      # We need repo files for the benchmark input files
      - uses: actions/checkout@v4
      - name: Download benchmark binaries
        uses: actions/download-artifact@v4
        with:
          name: benchmark-binaries
          path: ./bench_bin

      - name: Download poseidon-1000 files
        uses: actions/download-artifact@v4
        with:
          name: poseidon-1000-files
          path: ./poseidon-artifacts/

      - name: Setup rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v1
        with:
          channel: nightly-2025-04-05
          cache: false # We don't actually use any build files, no need to restore cache
          bins: cargo-codspeed

      - name: Create codespeed-post-bench symlink
        run: |
          # codspeed-post-bench is just a sym-link
          which codspeed-post-bench || echo "codspeed-post-bench not found"
          sudo ln -sf ~/.cargo/bin/cargo-codspeed /usr/local/bin/codspeed-post-bench
          ls -la /usr/local/bin/codspeed-post-bench

      - name: Copy binaries to target directory
        run: |
          mkdir -p target/codspeed
          cp -r bench_bin/* target/codspeed/

      - name: Make benchmark binaries executable
        run: chmod -R +x target/codspeed

      - name: Copy poseidon-rounds files to correct directory
        run: |
          cp ./poseidon-artifacts/noir-provekit-prover.pkp noir-examples/poseidon-rounds/
          cp ./poseidon-artifacts/noir-provekit-verifier.pkv noir-examples/poseidon-rounds/
          cp ./poseidon-artifacts/noir-proof.np noir-examples/poseidon-rounds/
          cp ./poseidon-artifacts/r1cs.json noir-examples/poseidon-rounds/
          ls -la noir-examples/poseidon-rounds/

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}
